config/routes.rb
JasmineCoffee::Application.routes.draw do
  resources :guitars

  root 'guitars#index'

end

app/models/guitar.rb
class Guitar < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :set_guitar, only: [:show, :edit, :update, :destroy]

  # GET /guitars
  # GET /guitars.json
  def index
    @guitars = Guitar.all
  end

  # GET /guitars/1
  # GET /guitars/1.json
  def show
  end

  # GET /guitars/new
  def new
    @guitar = Guitar.new
  end

  # GET /guitars/1/edit
  def edit
  end

  # POST /guitars
  # POST /guitars.json
  def create
    @guitar = Guitar.new(guitar_params)

    respond_to do |format|
      if @guitar.save
        format.html { redirect_to @guitar, notice: 'Guitar was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guitar }
      else
        format.html { render action: 'new' }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guitars/1
  # PATCH/PUT /guitars/1.json
  def update
    respond_to do |format|
      if @guitar.update(guitar_params)
        format.html { redirect_to @guitar, notice: 'Guitar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guitars/1
  # DELETE /guitars/1.json
  def destroy
    @guitar.destroy
    respond_to do |format|
      format.html { redirect_to guitars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guitar
      @guitar = Guitar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guitar_params
      params.require(:guitar).permit(:brand, :year, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/views/guitars/_form.html.erb
<%= form_for(@guitar) do |f| %>
  <% if @guitar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guitar.errors.count, "error") %> prohibited this guitar from being saved:</h2>

      <ul>
      <% @guitar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>

    <span class="guitar-age">
      Your guitar is <span id="age"></span> year(s) old
    </span>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guitars/edit.html.erb
<h1>Editing guitar</h1>

<%= render 'form' %>

<%= link_to 'Show', @guitar %> |
<%= link_to 'Back', guitars_path %>

app/views/guitars/index.html.erb
<h1>For Sale</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @guitars.each do |guitar| %>
      <tr>
        <td>
          <%= link_to guitar.title, guitar %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guitar', new_guitar_path %>

app/views/guitars/new.html.erb
<h1>New guitar</h1>

<%= render 'form' %>

<%= link_to 'Back', guitars_path %>

app/views/guitars/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @guitar.title %></h1>

<p>
  <strong>Brand:</strong>
  <%= @guitar.brand %>
</p>

<p>
  <strong>Year:</strong>
  <%= @guitar.year %>
</p>

<p>
  <strong>Title:</strong>
  <%= @guitar.title %>
</p>

<%= link_to 'Edit', edit_guitar_path(@guitar) %> |
<%= link_to 'Back', guitars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JasmineCoffee</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>